[patch.crates-io]
tiny-keccak = { git = "https://github.com/brevis-network/tiny-keccak", tag = "pico-patch-v1.0.0-keccak-v2.0.2" }
sha2 = { git = "https://github.com/brevis-network/hashes", rev = "2d0f0f9f4abde803c07801ca2fa02fd7911c6b30", package = "sha2" }
sha3 = { git = "https://github.com/brevis-network/hashes", tag = "pico-patch-v1.0.1-sha3-v0.10.8", package = "sha3" }
curve25519-dalek = { git = "https://github.com/brevis-network/curve25519-dalek", tag = "pico-patch-v1.0.1-curve25519-dalek-v4.1.3" }
ecdsa-core = { git = "https://github.com/brevis-network/signatures", tag = "pico-patch-v1.0.1-ecdsa-0.16.9", package = "ecdsa" }
substrate-bn = { git = "https://github.com/brevis-network/bn", tag = "pico-patch-v1.0.1-bn-v0.6.0" }
