[package]
name = "risc0-stateless-validator"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "^2.3.1", default-features = false, features = [
    "std",
    "unstable",
    "getrandom",
] }
guest-libs.workspace = true

reth-stateless.workspace = true
reth-ethereum-primitives = { workspace = true, features = [
    "serde",
    "serde-bincode-compat",
] }
reth-primitives-traits = { workspace = true, features = [
    "serde",
    "serde-bincode-compat",
] }
reth-evm-ethereum = { workspace = true }
reth-chainspec = { workspace = true }

revm = { workspace = true, features = ["std", "c-kzg", "blst", "bn"] }

alloy-primitives = { workspace = true, default-features = false, features = [
    "map-foldhash",
    "serde",
    "tiny-keccak",
] }
c-kzg = { version = "=2.1.1", default-features = true }

sha2 = "^0.10.8"
